repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: bash -c 'poetry run flake8 src'
        language: system
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash -c 'poetry run pytest'
        language: system
